repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.65.0
    hooks:
      - id: swiftlint
        entry: swiftlint --fix

  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.62.0
    hooks:
      - id: swiftformat
