excluded:
  - Package.swift
  - Tests
  - Tests/LinuxMain.swift
  - Tests/FinanceKitTests/XCTestManifests.swift

disabled_rules:
  - explicit_type_interface
  - extension_access_modifier
  - vertical_whitespace_between_cases

opt_in_rules:
  - custom_rules
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - boolean_return
  - class_delegate_protocol
  - class_name
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - compiler_protocol_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - documentation_ticks
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_acl
  - explicit_init
  - explicit_self
  - explicit_top_level_acl
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_length
  - file_name
  - file_name_no_space
  - file_types_order
  - final_class
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_https
  - force_try
  - force_unwrapping
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - no_fallthrough_only
  - no_space_in_method_call
  - notification_center_detachment
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_default_parameter
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - superfluous_disable_command
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - tabs
  - todo
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_contents_order
  - type_inferred_context
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition

# Configure Rules
force_unwrapping:
  severity: error
line_length:
  warning: 140
overridden_super_call:
  severity: error
prohibited_super_call:
  severity: error
identifier_name:
  excluded:
    - id
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  FinanceKit
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © 2020 Mitteldorf\. All rights reserved\.
                    \/\/

custom_rules: 
  boolean_return:
    name: "Boolean Return"
    regex: "\\? (true : false)|(false : true)"
    message: "It is redundant to return true or false for a boolean value. Instead return the value itself."
    severity: warning

  class_name:
    name: "Class Name"
    regex: "(?i)(class|struct) \\S*(Protocol|Delegate):"
    message: "A class name should never contain `Delegate` or `Protocol`. Use a Protocol instead."
    severity: warning

  documentation_ticks:
    name: "Documentation Ticks"
    regex: "´"
    message: "Incorrect Markdown format used. Mark types in '`' instead of '´' for proper formatting."
    match_kinds:
      - comment
      - doccomment
    severity: warning

  final_class:
    name: "Final Class"
    regex: "(?<!final )class (?!(\\{|private|func|var|.*XCTestCase))"
    message: "Classes not meant to be subclassed should be marked as `final`."
    match_kinds:
    - identifier
    - keyword
    - typeidentifier
    severity: warning

  force_https:
    name: "Force HTTPS"
    regex: "(?i)http:\\/\\/"
    message: "Using HTTP is not secure. Use HTTPS where possible."
    severity: warning
  logging:
    name: "Logging"
    regex: "(print|NSLog)\\("
    message: "Using print or NSLog is considered unsecure and inefficient. Use `os_log`"
    severity: warning

  # Custom rule violating if specifing a parameter to it's default value.
  redundant_default_parameter:
    name: "Redundant Default Value"
    regex: "(present|dismiss|animateWithDuration)\\(\\V*, completion: nil\\)"
    message: "Specifying a parameter with it's default value is redundant. Remove parameter or change it's value."
    severity: warning

  # Custom rule violating if tabs are used for indentation instead of spaces.
  tabs:
    name: "Tab Whitespace"
    regex: "\\t"
    message: "Using tabs is discouraged. Use spaces only."
    severity: warning

  # Custom rule violating when type inference is not used.
  # Violating:
  #   let view: UIView = UIView()
  #   view.backgroundColor = UIColor.red()
  # Non-violating:
  #   let view = UIView()
  #   view.backgroundColor = .red
  type_inferred_context:
    name: "type_inferred_context"
    regex: "(\\:\\s(\\w+)\\s\\=\\s\\1|\\.priority\\s\\=\\sUILayoutPriority\\.|(textColor|highlightedTextColor|tintColor|backgroundColor)\\s\\=\\sUIColor\\.|image\\s\\=\\sUIImage\\.|\\.alignmentMode\\s=\\sCATextLayerAlignmentMode\\.|separatorInset\\s=\\sUIEdgeInsets\\.|layoutMargins\\s=\\sUIEdgeInsets\\.)"
    message: "Type inferred context is preferred over explicit types."
    severity: warning

  todo_jira:
    name: "TODO without Clubhouse reference"
    regex: "(?i)(?=[^\\n]\\/\\/\\s+(TODO|TO DO|FIX|FIXME|FIX ME):)(?!.FKIT\\-\\d+)[^\\n]*"
    message: "Do not add TODOs without a task reference. Add Task Id to comment."
    severity: warning
