#if !canImport(ObjectiveC)
import XCTest

extension ChangeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChangeTests = [
        ("testEquatable", testEquatable),
        ("testInitWithNegativeChange", testInitWithNegativeChange),
        ("testInitWithPercentageValue", testInitWithPercentageValue),
        ("testInitWithPositiveChange", testInitWithPositiveChange),
        ("testIsNegative", testIsNegative),
        ("testIsPositive", testIsPositive),
        ("testPercentageText", testPercentageText),
        ("testZeroChange", testZeroChange),
    ]
}

extension CompanyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CompanyTests = [
        ("testComparable", testComparable),
        ("testEquatable", testEquatable),
        ("testInit", testInit),
    ]
}

extension CurrencyCodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CurrencyCodeTests = [
        ("testCurrencyCodeString", testCurrencyCodeString),
    ]
}

extension CurrencyPairTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CurrencyPairTests = [
        ("testInit", testInit),
    ]
}

extension CurrencyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CurrencyTests = [
        ("testCommonISOCurrencyCodes", testCommonISOCurrencyCodes),
        ("testInitWithCurrencyCode", testInitWithCurrencyCode),
        ("testISOCurrencyCodes", testISOCurrencyCodes),
        ("testLocaleCurrencyCode", testLocaleCurrencyCode),
        ("testLocaleCurrencySymbol", testLocaleCurrencySymbol),
        ("testLocalizedStringForCurrencyCode", testLocalizedStringForCurrencyCode),
        ("testName", testName),
        ("testNameWithUnknownCode", testNameWithUnknownCode),
    ]
}

extension DecimalDoubleValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecimalDoubleValueTests = [
        ("testDecimalDoubleValue", testDecimalDoubleValue),
    ]
}

extension HoldingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HoldingTests = [
        ("testAverageCostPerShare", testAverageCostPerShare),
        ("testChange", testChange),
        ("testChangeInLocalCurrency", testChangeInLocalCurrency),
        ("testComparable", testComparable),
        ("testDisplayNameWhenCompanyIsCompanyName", testDisplayNameWhenCompanyIsCompanyName),
        ("testDisplayNameWhenNoCompanyIsSymbol", testDisplayNameWhenNoCompanyIsSymbol),
        ("testEquatable", testEquatable),
        ("testInitWithDefaultValues", testInitWithDefaultValues),
        ("testInitWithValues", testInitWithValues),
        ("testMakeHoldingsPerformance", testMakeHoldingsPerformance),
        ("testMakeHoldingsWithBuyAndSellAndDividendTransactions", testMakeHoldingsWithBuyAndSellAndDividendTransactions),
        ("testMakeHoldingsWithBuyAndSellTransactions", testMakeHoldingsWithBuyAndSellTransactions),
        ("testMakeHoldingsWithBuyAndSellTransactionsInUnsortedOrder", testMakeHoldingsWithBuyAndSellTransactionsInUnsortedOrder),
        ("testMakeHoldingsWithNoTransactions", testMakeHoldingsWithNoTransactions),
        ("testMakeHoldingsWithOnlyBuyTransactions", testMakeHoldingsWithOnlyBuyTransactions),
        ("testMakeHoldingsWithOnlyDividendTransactions", testMakeHoldingsWithOnlyDividendTransactions),
        ("testMakeHoldingsWithOnlySellTransactions", testMakeHoldingsWithOnlySellTransactions),
        ("testUpdateWithStock", testUpdateWithStock),
        ("testUpdateWithStockWithDifferentSymbol", testUpdateWithStockWithDifferentSymbol),
    ]
}

extension PercentageFormatterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PercentageFormatterTests = [
        ("testStringFromPercentDouble", testStringFromPercentDouble),
    ]
}

extension PortfolioTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PortfolioTests = [
        ("testInit", testInit),
    ]
}

extension StockTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StockTests = [
        ("testEquatable", testEquatable),
    ]
}

extension SymbolTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SymbolTests = [
        ("testComparable", testComparable),
        ("testCustomStringConvertible", testCustomStringConvertible),
        ("testInitWithEmptyStringReturnsNil", testInitWithEmptyStringReturnsNil),
        ("testInitWithValidString", testInitWithValidString),
    ]
}

extension TransactionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransactionTests = [
        ("testInit", testInit),
        ("testTransactionCostBuy", testTransactionCostBuy),
        ("testTransactionCostDividend", testTransactionCostDividend),
        ("testTransactionCostSell", testTransactionCostSell),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ChangeTests.__allTests__ChangeTests),
        testCase(CompanyTests.__allTests__CompanyTests),
        testCase(CurrencyCodeTests.__allTests__CurrencyCodeTests),
        testCase(CurrencyPairTests.__allTests__CurrencyPairTests),
        testCase(CurrencyTests.__allTests__CurrencyTests),
        testCase(DecimalDoubleValueTests.__allTests__DecimalDoubleValueTests),
        testCase(HoldingTests.__allTests__HoldingTests),
        testCase(PercentageFormatterTests.__allTests__PercentageFormatterTests),
        testCase(PortfolioTests.__allTests__PortfolioTests),
        testCase(StockTests.__allTests__StockTests),
        testCase(SymbolTests.__allTests__SymbolTests),
        testCase(TransactionTests.__allTests__TransactionTests),
    ]
}
#endif
