# This workflow will build and test the package when pushing or merging to the main branch.

name: Main

on:
  push:
    branches: [ "master" ]

jobs:
  build-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test

  build-linux-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: swift build
    - name: Run Tests
      run: swift test

